### ISSUE TITLE
Dies in php 8

### ISSUE THREAD

**Issue by jjrohrer** [sc0ttkclark/papertrail#5]
When upgrading my server from 7.4 to PHP 8.0, I encountered this _(slightly edited)_
`Fatal error: Uncaught ArgumentCountError: Too few arguments to function WP_Papertrail_API::error_handler(), 4 passed and exactly 5 expected in /nas/content/live/ccc/WP_Papertrail_API.php:194 
`

I replaced, in `WP_Papertrails_API.php`, 
this
`   public static function error_handler( $id, $message, $file, $line, $context )
`
with
`
    public static function error_handler( $id, $message, $file, $line ) { 
`

Seems to work, but I'm not confident enough in this solution to post a Pull Request.
See also: [//https://stackoverflow.com/questions/65201307/too-few-arguments-to-function-exception-error-handler-php8](https://stackoverflow.com/a/65204532/93933)

**Comment by sc0ttkclark** [comment]
Thanks for the heads up! I'm going to revisit this code soon and test/fix PHP 8.0-8.1 compatibility.
